<?php
/**
 * DCP field groups
 *
 * @link https://www.advancedcustomfields.com/resources/???
 */

/**
 * Check if ACF PRO is active and function exists
 */

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
	return;
}

add_action( 'acf/include_fields', 'dcp_register_field_groups' );

function dcp_register_field_groups() {

	acf_add_local_field_group( array(
		'key' => 'group_63e510dd321c3',
		'title' => 'Content Collection Info',
		'fields' => array(
			array(
				'key' => 'field_63e510de57540',
				'label' => 'Collection Display Format',
				'name' => 'display_format',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'choices' => array(
					'grid' => 'Grid',
					'list' => 'List',
					'table' => 'Table',
					'archive' => 'Archive (Excerpts)',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63e5119557541',
				'label' => 'Aspect Ratio',
				'name' => 'aspect_ratio',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_63e510de57540',
							'operator' => '==',
							'value' => 'grid',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'choices' => array(
					'square' => 'Square',
					//'rectangle' => 'Rectangle',
					'portrait' => 'Portrait (2:3)',
					'landscape' => 'Landcape (16:9)',
				),
				'default_value' => 'landscape',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63e673a5c188e',
				'label' => 'Table Fields',
				'name' => 'table_fields',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_63e510de57540',
							'operator' => '==',
							'value' => 'table',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63e673b8c188f',
				'label' => 'Number of Columns',
				'name' => 'num_cols',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_63e510de57540',
							'operator' => '==',
							'value' => 'grid',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => 2,
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6463c3546a412',
				'label' => 'Note re title and image overrides',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'message' => '<div class="important" style="font-size:1.1rem">Please think twice or thrice before setting a title to override a <em>category name</em> or <em>post/page title</em> using the <strong>"Item Title"</strong> field. <strong>Do this only if absolutely necessary!</strong> Shortening is ok, but having basic consistency in titles from link to page will make the site easier to navigate. Likewise, for post object items, use the <strong>"Item Image"</strong> field <strong>ONLY</strong> if you wish to *override* any existing featured image.</div>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_63e51228f6684',
				'label' => 'Collection Items',
				'name' => 'collection_items',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => 'field_63e51876764fe',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_63e51247f6685',
						'label' => 'Item Type',
						'name' => 'item_type',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'choices' => array(
							'post' => 'Post (post, page, event...)',
							'post_category' => 'Post Category',
							'event_category' => 'Event Category',
							'page_link' => 'Page Link',
							'link' => 'Hyperlink',
							'email' => 'Email link',
							'modal' => 'Modal Content',
							'file' => 'Media File (PDF, image, audio file...)',
						),
						'default_value' => false,
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63e51876764fe',
						'label' => 'Item Title',
						'name' => 'item_title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63fe3187d32ca',
						'label' => 'Item Subtitle',
						'name' => 'item_subtitle',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_654013f322f45',
						'label' => 'Post Settings',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'placement' => 'top',
						'endpoint' => 0,
						'selected' => 0,
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63e512ebb35d3',
						'label' => 'Post Object',
						'name' => 'post_object',
						'aria-label' => '',
						'type' => 'relationship',
						'instructions' => 'For Item Type: Post',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'post_type' => array(
							0 => 'post',
							1 => 'page',
							2 => 'event',
							3 => 'person',
							4 => 'identity',
							5 => 'group',
							6 => 'repertoire',
							7 => 'liturgical_date',
							8 => 'sermon',
							9 => 'sermon_series',
							10 => 'event_series',
						),
						'post_status' => '',
						'taxonomy' => '',
						'filters' => array(
							0 => 'search',
							1 => 'post_type',
						),
						'return_format' => 'object',
						'min' => '',
						'max' => 1,
						'elements' => '',
						'bidirectional' => 0,
						'bidirectional_target' => array(
						),
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_654011ea3ea9c',
						'label' => 'Link Settings',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'placement' => 'top',
						'endpoint' => 0,
						'selected' => 0,
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63e5180a764fd',
						'label' => 'Link Target',
						'name' => 'item_link_target',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => 'For Item Type: Modal Content - or - Email Link',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'choices' => array(
							'_blank' => 'New Tab',
							'_self' => 'Same window (_self)',
							'modal' => 'Modal',
						),
						'default_value' => '_blank',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63e515c0131cc',
						'label' => 'URL',
						'name' => 'item_url',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => 'For Item Type: Hyperlink -- For external/absolute URLs only',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'placeholder' => '',
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63e5160c131cd',
						'label' => 'Email Address',
						'name' => 'item_email',
						'aria-label' => '',
						'type' => 'email',
						'instructions' => 'For Item Type: Email Link',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_641398160f1ea',
						'label' => 'Page Link',
						'name' => 'page_link',
						'aria-label' => '',
						'type' => 'page_link',
						'instructions' => 'For Item Type: Page Link',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'post_type' => '',
						'post_status' => '',
						'taxonomy' => '',
						'allow_archives' => 1,
						'multiple' => 0,
						'allow_null' => 0,
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_654012a0f22f1',
						'label' => 'Category Settings',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'placement' => 'top',
						'endpoint' => 0,
						'selected' => 0,
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63e51e2682aad',
						'label' => 'Post Category',
						'name' => 'post_category',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => 'For Item Type: Post Category',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'taxonomy' => 'category',
						'add_term' => 0,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'id',
						'field_type' => 'select',
						'allow_null' => 0,
						'bidirectional' => 0,
						'multiple' => 0,
						'bidirectional_target' => array(
						),
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63e51c2a81ec4',
						'label' => 'Event Category',
						'name' => 'event_category',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => 'For Item Type: Event Category',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'taxonomy' => 'event-categories',
						'add_term' => 0,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'id',
						'field_type' => 'select',
						'allow_null' => 0,
						'bidirectional' => 0,
						'multiple' => 0,
						'bidirectional_target' => array(
						),
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_640b3e9e46853',
						'label' => 'Category Image',
						'name' => '',
						'aria-label' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'message' => '<em>Images for taxonomy items are set via the taxonomy records themselves (e.g. https://stcnycstg.wpengine.com/wp-admin/term.php?taxonomy=category&tag_ID=1389)</em>',
						'new_lines' => 'wpautop',
						'esc_html' => 0,
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_6540135cf22f2',
						'label' => 'Content',
						'name' => '',
						'aria-label' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'placement' => 'top',
						'endpoint' => 0,
						'selected' => 0,
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63e518a3764ff',
						'label' => 'Item Image',
						'name' => 'item_image',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => 'For Item Type: Post Category - or - Event Category',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'return_format' => 'id',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'preview_size' => 'thumbnail',
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63e51b4a21171',
						'label' => 'Media File',
						'name' => 'media_file',
						'aria-label' => '',
						'type' => 'file',
						'instructions' => 'For Item Type: Media File',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'return_format' => 'array',
						'library' => 'all',
						'min_size' => '',
						'max_size' => '',
						'mime_types' => '',
						'parent_repeater' => 'field_63e51228f6684',
					),
					array(
						'key' => 'field_63e51a4404204',
						'label' => 'Item Content',
						'name' => 'item_content',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => 'For Item Type: Modal Content',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
						'parent_repeater' => 'field_63e51228f6684',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'collection',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

}

?>